name: storybook_flutter
description: A storybook for Flutter widgets. Live preview of isolated widgets
  for faster development and showcase.
version: 0.14.1
homepage: https://github.com/ookami-kb/storybook_flutter
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  device_frame:
    git:
      url: https://github.com/aloisdeniel/flutter_device_preview
      path: device_frame
      ref: 6d01e554963e03d0945d481876237c49d44b51ac
  flutter:
    sdk: flutter
  nested: ^1.0.0
  pointer_interceptor: '>=0.9.0 <0.11.0'
  provider: ">=6.0.0 <7.0.0"
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mews_pedantic: ^0.23.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
